#!/usr/bin/env python3
"""
Generate value_chart_teaser.html — a small, static, non-interactive top-N
preview of the auction value chart, for non-members. Meant to sit next to
value_chart.html on the same WordPress page, each wrapped in its own
[s2If] shortcode so S2Member shows exactly one of the two to a given
visitor. See CLAUDE.md for the member-gating setup.

Unlike value_chart.html, this doesn't need the full team/format-switching
JS or the embedded player dataset — it's a fixed 12-team/half-PPR snapshot,
regenerated by re-running this script whenever projections update.

Usage:
    python export_web_chart_teaser.py [N]
    python export_web_chart_teaser.py        # defaults to top 5
    python export_web_chart_teaser.py 10
"""

import sys
from pathlib import Path

from build_auction_values import blend_with_personal_ranks, load_personal_ranks, load_projections, compute_auction_values
from web_chart_utils import strip_blank_lines, collapse_script_style_blocks

HERE = Path(__file__).resolve().parent
OUT_FILE = HERE / "value_chart_teaser.html"

TOP_N = int(sys.argv[1]) if len(sys.argv) > 1 else 5

TEMPLATE = """<style>
  :root {{
    --bg: #ffffff; --surface: #ffffff; --surface-alt: #cccccc;
    --ink: #262625; --ink-soft: #6b6862; --ink-faint: #8a8a8a;
    --line: #d8d8d8; --accent: #cc5e03; --accent-ink: #ffffff;
    --qb: #ef74a1cc; --rb: #8ff2cacc; --wr: #56c9f8cc; --te: #feae58cc; --pos-ink: #000000;
    --radius: 3px; --shadow: 0 1px 2px rgba(28,35,31,.06), 0 6px 20px rgba(28,35,31,.05);
  }}
  * {{ box-sizing: border-box; }}
  .avc-teaser {{
    max-width: 640px; margin: 0 auto; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    color: var(--ink); background: var(--bg); padding: 24px; border-radius: var(--radius);
  }}
  .avc-teaser .eyebrow {{
    font-size: 11px; letter-spacing: .14em; text-transform: uppercase; color: var(--ink-faint);
    font-weight: 600; margin: 0 0 4px;
  }}
  .avc-teaser h2 {{
    font-family: Georgia, "Iowan Old Style", "Palatino Linotype", Palatino, serif;
    font-weight: 400; font-size: 22px; margin: 0 0 16px; text-wrap: balance;
  }}
  .avc-teaser table {{
    width: 100%; border-collapse: collapse; background: var(--surface);
    border: 1px solid var(--line); border-radius: var(--radius); overflow: hidden;
    font-variant-numeric: tabular-nums;
  }}
  .avc-teaser thead th {{
    text-align: left; font-size: 12px; letter-spacing: .04em; text-transform: uppercase;
    color: var(--accent-ink); font-weight: 700; padding: 10px 12px; background: var(--accent);
    border-bottom: 1px solid var(--accent);
  }}
  .avc-teaser tbody td {{ padding: 8px 12px; border-bottom: 1px solid var(--line); font-size: 14px; }}
  .avc-teaser tbody tr:last-child td {{ border-bottom: none; }}
  .avc-teaser td.player {{ font-weight: 600; }}
  .avc-teaser td.team {{ color: var(--ink-soft); font-size: 12.5px; }}
  .avc-teaser td.value {{
    font-family: ui-monospace, "SF Mono", "Cascadia Code", "Roboto Mono", Consolas, monospace;
    text-align: right; font-weight: 700; color: var(--accent);
  }}
  .avc-teaser .pos-chip {{
    display: inline-block; font-size: 11px; font-weight: 700; letter-spacing: .03em;
    padding: 2px 7px; border-radius: 999px; color: var(--pos-ink);
  }}
  .avc-teaser .pos-chip.QB {{ background: var(--qb); }}
  .avc-teaser .pos-chip.RB {{ background: var(--rb); }}
  .avc-teaser .pos-chip.WR {{ background: var(--wr); }}
  .avc-teaser .pos-chip.TE {{ background: var(--te); }}
  .avc-teaser .promo {{
    margin-bottom: 16px; padding: 14px 16px; border-radius: 6px;
    background: color-mix(in srgb, var(--accent) 10%, var(--surface));
    border: 1.5px solid var(--accent);
    font-size: 14px; color: var(--ink); line-height: 1.55;
  }}
  .avc-teaser .promo a {{ color: var(--accent); font-weight: 700; text-decoration: underline; }}
  .avc-teaser .promo .promo-code {{ font-weight: 700; color: var(--accent); }}
</style>
<div class="avc-teaser">
  <p class="eyebrow">Auction Draft Prep &middot; Preview</p>
  <h2>Top {top_n} Auction Values (12-Team, Half PPR)</h2>
  <p class="promo">Unlock Fantasy Six Pack&rsquo;s full Award-Winning Rankings by becoming an
  <a href="https://fantasysixpack.net/plans">All-Access Member</a>.<br />
  Use Promo Code <span class="promo-code">F6PRANKS</span> to save 15%!</p>
  <table>
    <thead><tr><th>#</th><th>Player</th><th>Team</th><th>Pos</th><th style="text-align:right;">Value</th></tr></thead>
    <tbody>
{rows}
    </tbody>
  </table>
</div>
"""

ROW_TEMPLATE = (
    '      <tr><td>{rank}</td><td class="player">{name}</td><td class="team">{team}</td>'
    '<td><span class="pos-chip {pos}">{pos}</span></td><td class="value">${value}</td></tr>'
)


def main():
    fmt = "half_ppr"
    projections = load_projections(fmt)
    personal_ranks = load_personal_ranks(fmt)
    blended = blend_with_personal_ranks(projections, personal_ranks)
    players, _ = compute_auction_values(blended, teams=12, verbose=False)
    players.sort(key=lambda p: -p["auction_value"])

    rows = "\n".join(
        ROW_TEMPLATE.format(rank=i, name=p["name"], team=p["team"], pos=p["position"],
                             value=round(p["auction_value"]))
        for i, p in enumerate(players[:TOP_N], start=1)
    )
    html = TEMPLATE.format(top_n=TOP_N, rows=rows)
    safe = strip_blank_lines(collapse_script_style_blocks(html))
    OUT_FILE.write_text(safe, encoding="utf-8")
    print(f"Wrote {OUT_FILE} (top {TOP_N}, 12-team half-PPR)")


if __name__ == "__main__":
    main()
