#!/usr/bin/env python3
"""Build the single WordPress embed from component.html.

One combined post (Standard/Half-PPR/PPR toggle, same JSON already has all
3 formats) -- the original 3-post split existed only because wp-datatables
was too slow to load every format's tables on one page at once. That's not
a constraint for a static-JSON + vanilla-JS grid, so this project
consolidates back to one post.

Same wpautop/force_balance_tags safety rules this repo already fought and
documented in ff_auction_values/web_chart_utils.py and ff_utilization/
component.html -- reused here rather than re-derived:
  1. collapse every <style>/<script> block to a single line (a line-based
     filter like wpautop has nothing to act on if there's no line break)
  2. strip every blank line from the whole file
  3. no `//` line comments anywhere in the JS (a collapsed newline would
     swallow the rest of the script) -- component.html has none, checked
  4. build table rows via createElement/textContent, never innerHTML
     string concatenation (force_balance_tags mangles tag-shaped JS string
     literals on save) -- component.html already does this

Usage:
    python build_embed.py
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "ff_auction_values"))
from web_chart_utils import collapse_script_style_blocks, strip_blank_lines  # noqa: E402

HERE = Path(__file__).resolve().parent
COMPONENT = HERE / "component.html"

# a `//` not immediately preceded by `:` (so `https://` survives)
_LINE_COMMENT_RE = re.compile(r"(?<!:)//")


def assert_safe(html):
    if "-->" in html.split("F6P_PA:START", 1)[0]:
        raise SystemExit("a '-->' appears before the start marker")
    if "s2If" in html:
        raise SystemExit("an s2If shortcode leaked into the embed")
    script = html.split("<script>", 1)[1].split("</script>", 1)[0]
    if _LINE_COMMENT_RE.search(script):
        raise SystemExit("a `//` line comment would swallow the rest of "
                          "the collapsed script")
    if re.search(r"['\"]<[a-zA-Z]", script):
        raise SystemExit("a tag-shaped JS string literal was found -- "
                          "build rows with createElement, not innerHTML")


def build():
    src = COMPONENT.read_text(encoding="utf-8")
    src = collapse_script_style_blocks(src)
    src = strip_blank_lines(src)
    banner = "<!-- F6P_PA:START (GENERATED by build_embed.py -- do not edit by hand) -->"
    out = banner + "\n" + src + "\n<!-- F6P_PA:END -->"
    assert_safe(out)
    return out


def main():
    out = build()
    dest = HERE / "embed.html"
    dest.write_text(out, encoding="utf-8")
    print(f"  {dest.name}  ({dest.stat().st_size/1024:.1f} KB)")


if __name__ == "__main__":
    main()
