#!/usr/bin/env python3
"""Build the WordPress embed from component.html.

Not the normal workflow for this project -- the user pastes component.html
directly into a Gutenberg Custom HTML block, which bypasses wpautop
entirely (confirmed on the sibling ff_points_against project). This script
exists only as a fallback for a Classic Editor Text-view paste, same
reasoning as that project's build_embed.py -- see its docstring for the
full wpautop/force_balance_tags history this reuses
(ff_auction_values/web_chart_utils.py).

Usage:
    python build_embed.py
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "ff_auction_values"))
from web_chart_utils import collapse_script_style_blocks, strip_blank_lines  # noqa: E402

HERE = Path(__file__).resolve().parent
COMPONENT = HERE / "component.html"

_LINE_COMMENT_RE = re.compile(r"(?<!:)//")


def assert_safe(html):
    if "-->" in html.split("F6P_IDP:START", 1)[0]:
        raise SystemExit("a '-->' appears before the start marker")
    if "s2If" in html:
        raise SystemExit("an s2If shortcode leaked into the embed")
    script = html.split("<script>", 1)[1].split("</script>", 1)[0]
    if _LINE_COMMENT_RE.search(script):
        raise SystemExit("a `//` line comment would swallow the rest of "
                          "the collapsed script")
    if re.search(r"['\"]<[a-zA-Z]", script):
        raise SystemExit("a tag-shaped JS string literal was found -- "
                          "build rows with createElement, not innerHTML")


def build():
    src = COMPONENT.read_text(encoding="utf-8")
    src = collapse_script_style_blocks(src)
    src = strip_blank_lines(src)
    banner = "<!-- F6P_IDP:START (GENERATED by build_embed.py -- do not edit by hand) -->"
    out = banner + "\n" + src + "\n<!-- F6P_IDP:END -->"
    assert_safe(out)
    return out


def main():
    out = build()
    dest = HERE / "embed.html"
    dest.write_text(out, encoding="utf-8")
    print(f"  {dest.name}  ({dest.stat().st_size/1024:.1f} KB)")


if __name__ == "__main__":
    main()
