#!/usr/bin/env python3
"""Generate the two WordPress post blocks from component.html.

One component, one data file, two posts: the weekly-usage post and the
season-long-usage post. Each generated file is the complete block to paste
into that post -- markup, style and script, nothing external except the
Google Fonts import.

Output:
    embed_weekly.html   -> paste into the weekly usage post
    embed_season.html   -> paste into the season-long usage post
    usage_table.html    -> local dev copy (both views, reads data/ over HTTP)

Usage:
    python build_embed.py
    python build_embed.py --data-url "/?s2member_file_download=utilization_weekly.json"
"""

import argparse
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
COMPONENT = HERE / "component.html"
TEASER_COMPONENT = HERE / "component_teaser.html"
KEY_COMPONENT = HERE / "component_key.html"

# The teaser JSONs canNOT live behind the s2member gateway -- that gateway
# checks membership before serving ANYTHING in its folder, gating the teaser
# file too and defeating the point. They need their own plain, public paths.
# Two files (weekly / season), matching the two member posts they sit under.
DEFAULT_TEASER_URLS = {
    "weekly": "/wp-content/uploads/f6p-data/utilization_teaser_weekly.json",
    "season": "/wp-content/uploads/f6p-data/utilization_teaser_season.json",
}

# wpautop-proofing. The site edits posts through the Classic Editor's Text
# view, which -- unlike a Gutenberg Custom HTML block -- does NOT bypass
# wpautop() on the front end. wpautop wraps blank-line-separated content in
# <p> tags and has a long history of doing that INSIDE <script>/<style>,
# corrupting the JS/CSS. ff_auction_values fought this for four rounds; the
# settled fix is to leave no line boundaries inside those tags at all, so a
# line-based filter has nothing to act on. See web_chart_utils.py there for
# the full history, including the base64 self-loader dead end.
_BLOCK_RE = re.compile(r"(<style[^>]*>|<script[^>]*>)(.*?)(</style>|</script>)",
                       re.DOTALL)
_LINE_COMMENT_RE = re.compile(r"(^|[^:\"'])//")


def collapse_script_style_blocks(html):
    """Squash each <style>/<script> body to a single line."""
    def _collapse(match):
        open_tag, body, close_tag = match.groups()
        return open_tag + re.sub(r"\s+", " ", body).strip() + close_tag
    return _BLOCK_RE.sub(_collapse, html)


def assert_no_line_comments(html, name):
    """Collapsing turns newlines into spaces, so a surviving "//" comment would
    silently swallow the rest of the script. Block comments only. Checked on
    <script> bodies before collapsing; the guard character class keeps
    "https://" and "url(https://...)" from tripping it."""
    for body in re.findall(r"<script[^>]*>(.*?)</script>", html, re.DOTALL):
        for num, line in enumerate(body.splitlines(), 1):
            if _LINE_COMMENT_RE.search(line):
                raise AssertionError(
                    f"{name}: '//' line comment in <script> line {num} -- "
                    f"convert it to /* */ in component.html, or collapsing "
                    f"will eat the rest of the file:\n    {line.strip()[:90]}")

# s2Member serves anything in /wp-content/plugins/s2member-files/ only through
# this gateway, checking membership on every request. Same-origin, so the
# browser sends the session cookie and fetch() needs no extra credentials.
DEFAULT_URL = "/?s2member_file_download=utilization_weekly.json"

# cache:"no-cache" revalidates rather than pinning a ?v= in the URL, so a fresh
# upload is picked up with no code change and an unchanged file returns 304.
FETCH = ('fetch("{url}", {{cache:"no-cache"}}).then(function(r){{'
         'if(!r.ok){{throw new Error("HTTP "+r.status);}}return r.json();}})')

# Single line, and it must contain NEITHER a nested "-->" NOR an s2If
# shortcode. HTML comments don't nest: an inner "-->" closes the outer comment
# early, dumping the rest of the banner on the page as visible text -- and a
# stray [/s2If-paywall] inside it closes the real paywall block early, so the
# component never initializes. That shipped once; keep this line dumb.
# Paste instructions live in PASTE_INSTRUCTIONS.txt, not in the file itself.
BANNER = ("<!-- F6P {which} usage table. Generated by build_embed.py from "
          "component.html - do not edit here. -->\n")


def build(view, data_source, collapse=True):
    src = COMPONENT.read_text(encoding="utf-8")
    start = src.index("<!-- F6P_USAGE:START -->")
    body = (src[start:].replace("__VIEW_MODE__", view)
                       .replace("__DATA_SOURCE__", data_source))
    assert_no_line_comments(body, f"{view} embed")
    if collapse:
        body = collapse_script_style_blocks(body)
        # Blank lines anywhere in the pasted block can trigger wpautop right at
        # a tag boundary -- that's what defeated round 1 of the auction-chart
        # fix, where <p><script> appeared despite the script itself being clean.
        body = "\n".join(ln for ln in body.splitlines() if ln.strip())
    return body


def build_key(collapse=True):
    """The column-definition key. Same content regardless of membership, so
    it is built once and placed once -- not duplicated inside the member and
    teaser components the way it briefly was."""
    src = KEY_COMPONENT.read_text(encoding="utf-8")
    start = src.index("<!-- F6P_KEY:START -->")
    body = src[start:]
    assert_no_line_comments(body, "stat key embed")
    if collapse:
        body = collapse_script_style_blocks(body)
        body = "\n".join(ln for ln in body.splitlines() if ln.strip())
    return body


def build_teaser(weekly_url, season_url, collapse=True):
    src = TEASER_COMPONENT.read_text(encoding="utf-8")
    start = src.index("<!-- F6P_TEASER:START -->")
    body = (src[start:].replace("__TEASER_WEEKLY_URL__", weekly_url)
                       .replace("__TEASER_SEASON_URL__", season_url))
    assert_no_line_comments(body, "teaser embed")
    if collapse:
        body = collapse_script_style_blocks(body)
        body = "\n".join(ln for ln in body.splitlines() if ln.strip())
    return body


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-url", default=DEFAULT_URL)
    ap.add_argument("--teaser-url-weekly", default=DEFAULT_TEASER_URLS["weekly"])
    ap.add_argument("--teaser-url-season", default=DEFAULT_TEASER_URLS["season"])
    ap.add_argument("--dev-data", default="data/utilization_weekly_2025_wk1-2.json")
    args = ap.parse_args()

    live = FETCH.format(url=args.data_url)

    def write_checked(name, which, marker, text):
        # Guard the failure above can't be allowed to recur: nothing outside the
        # component's own START/END markers may contain a comment terminator,
        # and no s2If shortcode may appear anywhere in the file.
        head = text[:text.index(marker)]
        assert "-->" not in head.replace(BANNER.format(which=which), ""), \
            f"{name}: stray '-->' before the start marker"
        assert "s2If" not in text, f"{name}: s2If shortcode leaked into {name}"
        out = HERE / name
        out.write_text(text, encoding="utf-8")
        print(f"{name:<24} {out.stat().st_size/1024:>5.1f} KB")
        return out

    for view, name, which in (
        ("weekly", "embed_weekly.html", "weekly"),
        ("season", "embed_season.html", "season-long"),
        # One page, one component instance, Weekly/Season built in as a
        # segmented toggle -- no Gutenberg tabs plugin, no fetching the data
        # twice. This is what actually goes on the single tool page; the two
        # single-view embeds above are kept in case a split page is ever
        # wanted again, not because both get published.
        ("both", "embed_combined.html", "combined weekly + season"),
    ):
        text = BANNER.format(which=which) + build(view, live)
        write_checked(name, which, "<!-- F6P_USAGE:START -->", text)

    # ONE teaser now, with its own Weekly/Season toggle, matching the ONE
    # combined member table -- there is exactly one page, so there must be
    # exactly one non-member view of it too, not one per (now-nonexistent)
    # single-view page.
    teaser_text = (BANNER.format(which="non-member teaser (weekly + season toggle)")
                   + build_teaser(args.teaser_url_weekly, args.teaser_url_season))
    write_checked("embed_teaser_combined.html",
                  "non-member teaser (weekly + season toggle)",
                  "<!-- F6P_TEASER:START -->", teaser_text)

    # Shared stat-definition key -- ONE copy, same for every visitor
    # regardless of membership, so it isn't built per-audience.
    key_text = BANNER.format(which="stat key (shared, all audiences)") + build_key()
    write_checked("embed_key.html", "stat key (shared, all audiences)",
                  "<!-- F6P_KEY:START -->", key_text)

    # Dev copy stays uncollapsed -- it never goes through WordPress, and
    # readable source is what makes it useful for debugging.
    dev = HERE / "usage_table.html"
    dev.write_text(
        "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
        "<title>F6P Usage — local dev</title></head><body>\n"
        "<!-- GENERATED by build_embed.py. Needs a web server for the relative\n"
        "     fetch: python -m http.server 8765 -->\n"
        + build_key(collapse=False) + "\n"
        + build("both", FETCH.format(url=args.dev_data), collapse=False)
        + "\n</body></html>\n",
        encoding="utf-8")
    print(f"{'usage_table.html':<24} {dev.stat().st_size/1024:>5.1f} KB   "
          f"(local dev, both views)")

    dev_teaser = HERE / "teaser_preview.html"
    dev_teaser.write_text(
        "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
        "<title>F6P Teaser — local dev</title></head><body>\n"
        "<!-- GENERATED by build_embed.py. Needs a web server for the relative\n"
        "     fetch: python -m http.server 8765 -->\n"
        + build_key(collapse=False) + "\n"
        + build_teaser("data/utilization_teaser_weekly.json",
                       "data/utilization_teaser_season.json", collapse=False)
        + "\n</body></html>\n",
        encoding="utf-8")
    print(f"{dev_teaser.name:<24} {dev_teaser.stat().st_size/1024:>5.1f} KB   "
          f"(local dev, teaser w/ toggle)")

    # THE single deliverable: the one page's full paste-ready source, both
    # audiences, in one file. Strip our own build banner from each piece --
    # it's a build-log line, not something that belongs in published content.
    def stripped(text):
        lines = text.splitlines()
        if lines and lines[0].startswith("<!-- F6P"):
            lines = lines[1:]
        return "\n".join(lines)

    member_block = stripped(BANNER.format(which="combined weekly + season")
                             + build("both", live))
    teaser_block = stripped(teaser_text)
    key_block = stripped(key_text)
    # Key sits ABOVE both shortcodes -- outside the paywall gate entirely, and
    # above the Weekly/Season toggle inside each -- since the definitions are
    # the same for a member or a visitor and shouldn't be duplicated per
    # audience just because the table beneath them is.
    page = (f"{key_block}\n\n"
            f"[s2If-paywall]\n{member_block}\n[/s2If-paywall]\n\n"
            f"[s2If-ads]\n{teaser_block}\n[/s2If-ads]\n")
    assert page.count("[s2If-paywall]") == 1 and page.count("[/s2If-paywall]") == 1
    assert page.count("[s2If-ads]") == 1 and page.count("[/s2If-ads]") == 1
    page_path = HERE / "wp_page.html"
    page_path.write_text(page, encoding="utf-8")
    print(f"\n{page_path.name:<24} {page_path.stat().st_size/1024:>5.1f} KB   "
          f"<-- paste this whole file into the ONE post")

    print(f"\nlive data URL:          {args.data_url}")
    print(f"teaser data URL (wk):   {args.teaser_url_weekly}")
    print(f"teaser data URL (szn):  {args.teaser_url_season}")


if __name__ == "__main__":
    main()
